profanity_words = ['Shit', 'shit,', 'Mother-fucker', 'fuck,', 'fucking,', 'pissings', 'bitcheries', 'Slut', 'sluts',
                   'Sh*thead', 's**rew', 'B**bs', 'Hell', 'D*ick', 'c*t', 'cunts', 'Holy Shits', 'fuck Jesus',
                   'Niggers', 'F***', 'god damns', 'Holy cow', 'goddamns', 'whores', 'pissing', 'Screwed', 'fucks',
                   'bitching', 'goddamned', 'Holy Sh*t', 'shitbag', 'Cock suckers', 'c**t', 'whoredoms',
                   'Holy balls', 'sucker', 'shitheads', 'Bullshit', 'f-words', 'Cunt', 'Shithead', 'Cocksuckers',
                   't*its', 'god damms', 'suckers', 'asses', 'Crappy', 'P*ssy', 'p*ssy', 'fag', 'Holy crap', 'tits',
                   'Tits', 'F*ck', 'bull shit', 'shit head', 'damned', 'Sucks', 'f*ck Jesus', 'Fuckface', 'Nigga',
                   'HolyShit', 'D*ickhead', 'bastardizing', 'sucked', 'whored', 'B-tch', 'Fuck!', 'Bitch',
                   'sucking',
                   'twats', 'f-ck', 'motherfuckers', 'bullshitting',
                   'pissers', 'boobs', 'Bull-Shit', 'Titties', 'B*tch', 'Mother fucking', 'bastardisations', 'pisser',
                   'Whore', 'balls', 'fucking Christ', 'goddamm', 'sh*t', 'b**bs', 'Cock sucker', 'whoredom',
                   'a**hole', 'bastardly', 'f-word', 'bastardize', 'Asshole',
                   'HolyShits', 'Bullsh*t', 'For Satan Sake', 'bastardizes', 'Damn', 'Holy Shit', 'goddamms',
                   'Butt Hole', 'Hail-Satan', 'a**', 'bastardization', 'f*cking', 'F**k', 'Ass-hole', 'shitting', 'Booby', 'twat', "fuckin'",
                   'fucking Jesus', 'Bitches', 'Bull shits', 'Damm-its', 'dickheads', 'bastardisation', 'Goddamnit', 'fucked', 'ass holes', 'Twat', 'boobed',
                   'MotherF**ker', 'p**sy', 'C*nt', 'f**ck', 'fuck', 'Fuckery', 'god damm', 'boobies', 'Mother fuckers', 'cock', 'clusterfuck',
                   'shits', 'MotherF*cker', 'Dammits', 'dong', 'bitchinesses', 'c*ck', 'Dicks', 'Faggot', 'fuckup', 'fucking', 'Mother fucker',
                   'f*cking Christ', 'kickass', 'boobing', 'boobie', 'Ass', 'God damn it', 'mother fuckers', 'bo**bs',
                   'Damn It', 'whoring', 'Dick', 'Ballsy', 'Cock-sucker', 'jackass', 'Slutty', 'Piss', 'Bastard',
                   'assholes', 'shitters', 'fucking Lord', 'Cocksucker', 'Arsehole', 'fuckin', 'badass', 'faggots',
                   'Pussy', 'bastardized', 'Damn-It', 'Prick', 'whore',
                   'fuck sake', 'bastardise', 'bitchy', 'bullshitters', 'Twats', 'f**ed', "For Satan's Sake",
                   'Damnits', 'bitchery', 'pissed', "motherfucker's",
                   'bastardizations', 'God Damn', 'bullshit', 'shithole', 'Niggas', 'motherfucking', 'Shitty',
                   'Sweet Jesus', 'bitched', 'pussy', 'f*cking God', 'f**',
                   'god damn', 'goddamn', 't**at', 'Nigger', 'bitchiness', 'tit', 'pussies', 'Dammit', 'butt',
                   'shit heads', 'dick', 'ass hole', 'damns', 'Hail Satan',
                   'Craps', 'goddammit', 'boob', 'Boobs', 'God damnit', 'god dammit', 'shitter', 'pisses',
                   'screw', 'bullshitted', 't**t', 'Screws', 'Cu*t',
                   'Damnit', 'fuckhead', 'Motherfuckin', 'fucking God', 'shittings', 'screws', 'Crap', 'fucker',
                   'F-Word', 'damning', 'Shit', 'bastards', 'bullshits',
                   'Mother of God', 'Screw', 'godamned', 'Dickhead', 'Motherfucker', 'Arse-hole', 'd**k', 'suck']
